mintest.pdf: mintest.tex intro.tex bibliography.bib casestudies.tex covmin.tex related.tex abstract.tex conclusions.tex *.table sir.tex spidermonkey.tex opensource.tex formal.tex graphs/*.pdf siemens1.pdf siemens2.pdf naspidermonkey.pdf
	pdflatex mintest.tex
	bibtex mintest
	pdflatex mintest.tex
	pdflatex mintest.tex